### ISSUE TITLE
Deprecate primitive-0.6.2.0 and 0.6.3.0

### ISSUE THREAD

**Issue by cartazio** [haskell/primitive#105]
@treeowl  @andrewthad @RyanGlScott 

i'm now on the uploaders, 
which bug fixes should we backport to which major versions?
direct me and I'll make it so !

**Comment by treeowl** [comment]
Thankfully, the problems all showed up in the last two versions, as far as I know. Basically, `Functor`, `Applicative`, `Monad`, `Foldable`, and `IsList` need changing. Apparently `Foldable` isn't yet fixed (whoops), and `IsList` has some open questions. I think we should start branches for the backports so we can get on the same page.

**Comment by andrewthad** [comment]
I'm not totally convinced that we need backports. I think we can just deprecate `0.6.2` and `0.6.3` in favor of `0.6.4`. But yes, everything David mentioned needs fixing.

**Comment by treeowl** [comment]
I'd be fine with just deprecating. Backporting would be work.

**Comment by cartazio** [comment]
oh, i thought you meant the bug was in 0.5 Primitive.

**Comment by hvr** [comment]
Btw, the changelog at

https://github.com/haskell/primitive/blob/master/changelog.md#changes-in-version-0640

just says "broken instances"; given the importance of `primitive`, we ought to say a bit more how exactly this is considered broken;

also it's not clear to me what you mean by "deprecating"; is this just "soft deprecating" (which has a very modest/weak effect), or "hard deprecation" (retroactively blacklisting a release so that the solver cannot select it anymore).

**Comment by treeowl** [comment]
@hvr I am not familiar with the detailed effects of soft deprecation. Perhaps you can explain further? I would very much prefer if the solver did not accept it without a user override; the bugs are of a fairly scary variety.

**Comment by hvr** [comment]
@treeowl so what you want is the "hard deprecation" which currently can be achieved by cabal revisions; the effect is that you won't be able to install the deprecated releases w/o using e.g. `--allow-newer=primitive-0.6.3:base`; but I agree w/ @andrewthad that we should first rls 0.6.4 to avoid the confusion.

**Comment by treeowl** [comment]
Yes, of course. Let's get that ready first. I think we're close.

**Comment by cartazio** [comment]
OK: what commits do we need to apply on top of 0.6.2 for the 0.6.3?

@hvr @treeowl @andrewthad  please point out which should be applied, and i'll perpare a branch and tag and release

**Comment by cartazio** [comment]
*which commits need be applied

**Comment by cartazio** [comment]
i'm tentatively thinking 64aade4305f8249bb7458ed776da26c00753863a

**Comment by treeowl** [comment]
Carter, Andrew and I thought the plan was not to try to fix those old
versions. You're not going to be able to fix them by cherry-picking
commits. There are bug fixes spread through various recent commits that
also do other things.

**Comment by andrewthad** [comment]
I agree with David. I think we can  basically just cut a release from master and call it 0.6.4.0.  The only thing that I want to settle first is the naming of unsafeTraverseArray.  It hasn’t been released yet, so we can still change it without that being a breaking change.  My work in the primitive array branch would suggest that this function be named traverseArrayP  instead.  I don’t particularly mind which naming convention we adopt.  But, the decision needs to be made before the next release, because changing it after that point would be a breaking change.

**Comment by cartazio** [comment]
Ok good point.

**Comment by cartazio** [comment]
I didn’t say fix. I just was propsosing a base commit / root for the new
release

**Comment by cartazio** [comment]
I’ll make some notes / think about this more and get back to y’all

**Comment by andrewthad** [comment]
@hvr writes:

> we ought to say a bit more how exactly this is considered broken

I've done this in https://github.com/haskell/primitive/pull/133

**Comment by andrewthad** [comment]
These versions were deprecated a while ago. Closing.
