### ISSUE TITLE
Expand the test suite

### ISSUE THREAD

**Issue by treeowl** [haskell/primitive#111]
We at least need to test `MonadZip`, `Alternative`, and `MonadPlus` instances.

**Comment by andrewthad** [comment]
I've added laws for `MonadZip` (well, only one of its two laws since the other would used implication and the predicate is hard to satisfy) and `MonadPlus` to `quickcheck-classes`, and I discovered that @chessai had already added laws for `Alternative` that I had forgotten about. After the next release of `quickcheck-classes`, I'll add these checks for `Array` and `SmallArray`.

**Comment by treeowl** [comment]
I think we probably also want tests like containers comparing what
functions and methods here do to what the corresponding ones for lists do.

**Comment by treeowl** [comment]
Indeed, we could probably port a bunch of tests over from containers and/or
vector.

**Comment by chessai** [comment]
MonadZip, Alternative, and MonadPlus should be really easy to add tests for, since they are all implemented in quickcheck-classes-base
