### ISSUE TITLE
add to 0.6.4 changelog : Mvars!

### ISSUE THREAD

**Issue by cartazio** [haskell/primitive#171]

**Comment by cartazio** [comment]
cc @andrewthad  we forgot!

**Comment by andrewthad** [comment]
I'll do this now.

**Comment by andrewthad** [comment]
Added by https://github.com/haskell/primitive/pull/172

**Comment by cartazio** [comment]
should we add a 0.6.4.1 entry:
adding changelog entry for Mvar to 0.6.4.0 changelog
:)

**Comment by andrewthad** [comment]
Probably

**Comment by winterland1989** [comment]
I'm curious what's the use case of this? I think there're some problems:

+ `ST` is all about seal its `State#` token, it shouldn't be used when concurrent needed. If there's a need purely to hidden away `IO` in some data structure, unsafely using `ST` is not different from using `unsafePerformIO`. 

+ `ST` don't have exception handling capability, adding it will be more trouble than it really worth IMHO, and this stop us using `MVar` safely.

+ If any custom monad need this generalized APIs, i suspect it can always be implemented with a transformer over `IO`,  this is how IO effect is supposed to be handled.

I'm afraid the generalized operations will only bring confusions with `Control.Concurrent.MVar` and not worth the trouble since the operations are using all the same names. I really feel we should consider withdraw this API. But if there're some real world use case, please let me know.

**Comment by andrewthad** [comment]
I make use of the `MVar` stuff in the `primitive-sort` package. Look at the master branch instead of the hackage release. Users who want to get any utility out of this will probably need to write:

```
forkST_ :: ST s a -> ST s ()
forkST_ action = ST $ \s1 -> case forkST# action s1 of
  (# s2, _ #) -> (# s2, () #)

forkST# :: a -> State# s -> (# State# s, ThreadId# #)
forkST# = unsafeCoerce# fork#
```

And then you can build things like this:

```
-- | Execute the first computation on the main thread and
--   the second one on another thread in parallel. Blocks
--   until both are finished.
tandem :: ST s () -> ST s () -> ST s ()
tandem a b = do
  lock <- newEmptyMVar
  forkST_ (b >> putMVar lock ())
  a
  takeMVar lock
```

The user has to prove that the actions they run in tandem don't interfere with each other. Sorts that have a merge step work well with this:

```
-- arguments: array, inclusive low index, exclusive high index
sortRange :: MutableArray s a -> Int -> Int -> ST s ()
sortRange = ...

sortTwoThousand :: MutableArray s a -> ST s ()
sortTwoThousand arr = do
    tandem (sortRange arr 0 1000) (sortRange arr 1000 2000)
    mergeAdjacentRanges 0 1000 2000
```

My `primitive-sort` library uses a more complicated variant of this technique to improve mergesort on boxes with many cores.

> `ST` is all about seal its `State#` token, it shouldn't be used when concurrent needed. If there's a need purely to hidden away `IO` in some data structure, unsafely using `ST` is not different from using `unsafePerformIO`. 

We don't want to general `IO` in the forked computation. Notice that the type of `forkST` doesn't allow mutable variables to escape a `runST`. It does introduce an opportunity for nondeterminism, and the user bears the burden of proving that they don't use it to produce this kind of behavior.

> `ST` don't have exception handling capability, adding it will be more trouble than it really worth IMHO, and this stop us using `MVar` safely.

Yes, `ST` doesn't have any exception-handling capabilities, but this doesn't actually pose a problem with `forkST`. Since we throw away the thread id, that no one can kill the thread. A hypothetical `killThreadST` would be nearly impossible (or totally impossible) to use in a way that didn't introduce non-determinism.

**Comment by cartazio** [comment]
indeed, and theres also disciplined patterns of forkJOIN using write once
MVars that can also be used here

**Comment by winterland1989** [comment]
> My primitive-sort library uses a more complicated variant of this technique to improve mergesort on boxes with many cores.

Generally I don't know if it is a good idea to spawn many haskell threads when evaluate the `ST` expression. The difference between `IO` and `ST` is quite clear from haskell report,  `forkST` kind of breaks my expectation. After all sorting mutable array in parallel in `IO` makes sense isn't it, i don't think doing this in mono `IO` will cause any trouble to user.

And I still feel the naming conflict with `Control.Concurrent.MVar` is really unfortunate, i didn't see any discussion on library mailing list about this, maybe we should start one.

**Comment by andrewthad** [comment]
Using GHC's primitives for sparks does not work well for parallelizing a task on a mutable array. I've tried doing this before, and it didn't work. Other people seem to have had various [successes with it](https://unlines.wordpress.com/2010/04/21/sparking-imperatives/), but I found it extremely difficult to reason about. You still have to worry about all the same concurrency-related issues that show up when using `forkST` and `MVar`, but then you also have to worry about [the scheduler not starting sparks promptly](https://stackoverflow.com/questions/46586941/why-are-ghc-sparks-fizzling) and forcing thunks to guarantee that an action gets executed.

It does make sense to perform a parallel sort in `IO`, but `IO` lets me do too much. I don't want to be able to access the file system in this computation. I just want locally-scoped mutation, and I want parallelism. By extending `ST` with `forkST`, I take on the burden of proving that my computation is deterministic, but I don't open myself up to everything that `IO` would allow me to do.

The naming conflict is unfortunate, but there's not really a better name for this. By convention, `primitive` names everything in a way that matches the underlying primitive type:

- `MutVar#`: `MutVar`
- `Array#`: `Array`
- `MutableByteArray#`: `MutableByteArray`

It would be strange to call it anything else. Feel free to start a discussion on the mailing list, but it's unlikely that this will be changed at this point unless there is some serious blacklash against this.

**Comment by winterland1989** [comment]
@andrewthad , I think it’s definite a ghc scheduler bug, we should always run the spark thread just like it’s a normal Haskell thread, I’ll try to follow it on ghc trac.

The cost is easy to reason about actually, sparks only cost you one extra thread, thus saves the cost of creating `TSO`, especially the memory overhead, the context switch overhead may be ignored if you choose a very large partition size, but that will also make the parallel sort unpractical. Overall I’m very skeptical about using explicit multi thread techniques in data parallel scenarios, it’s just too heavy weight. Thus I strongly suggest you to give `par` a try once we make the sparks scheduling right.

Overall I feel it’s been settled with current APIs, so let’s focus on other issues brought by this mega release ; )
