### ISSUE TITLE
Read Array instance fails in record context

### ISSUE THREAD

**Issue by skeuchel** [haskell/primitive#223]
When putting an Array into a record field, the show/read roundtrip fails. The following program

```
import Data.Primitive.Array

data Record = Record { field :: Array Int }
  deriving (Read, Show)

r :: Record
r = Record $ fromListN 0 []

main :: IO ()
main = print (read (show r) :: Record)
```

when run produces
```
λ> main
*** Exception: Prelude.read: no parse
```

**Comment by skeuchel** [comment]
The issue is here https://github.com/haskell/primitive/blob/master/Data/Primitive/Array.hs#L788

The record inserts a whitespace but doesn't consume it, leaving it to the Read instance of Array which doesn't like initial whitespace
```
λ> read "fromListN 0 []" :: Array Int
fromListN 0 []
λ> read " fromListN 0 []" :: Array Int
fromListN *** Exception: Prelude.read: no parse
```
The same line has another "bug" because it doesn't properly lex the identifier:
```
λ> read "fromListN0 []" :: Array Int
fromListN 0 []
```
I can create a PR that either does the minimal work to correct this or replace the Read/Read1 instances with more efficient ReadPrec variants. What do you prefer?

**Comment by andrewthad** [comment]
Good catch. Concerning which string parser is used, I’m indifferent. But do make sure to add a test. We’re using quickcheck-classes in the test suite, so adding a check for Show/Read roundtripping is trivial.

**Comment by chessai** [comment]
Nice catch. Thanks for this

**Comment by cartazio** [comment]
question: why dont we just move to using the deriving instances for these?

**Comment by cartazio** [comment]
it occurs to me this exact same issue should be happening in vector and
containers, or has it be fixed there too? (the point is theres some
commonality)

**Comment by skeuchel** [comment]
The Read Set instance in containers 
https://github.com/haskell/containers/blob/36bff81bad71a9727b811bd8004ba92d824fbe29/Data/Set/Internal.hs#L1133-L1146
is fine and Vector is outputting lists without any "fromList" prepended.

**Comment by skeuchel** [comment]
@andrewthad I'm actually preparing a bigger PR for quickcheck-classes in a separate branch https://github.com/andrewthad/quickcheck-classes/tree/showread which revealed this issue.

**Comment by cartazio** [comment]
Oh yeah.

Why aren’t we using is/from list type classes ?

**Comment by andrewthad** [comment]
@cartazio It is not possible to derive these instances. The stock deriving strategy requires that all of the things inside have the instances of the typeclass  you are trying to derive. And Array#  does not have a Show/Read instance.

**Comment by treeowl** [comment]
We should probably use a `ReadPrec`-based instance, since the derived stuff will probably use that more efficiently. `Read` instances should be flexible about whitespace, so something like `"   fromListN   0[3]"` should work. Furthermore, `Read` instances should generally aim to be tolerant and human-friendly, so I think we should accept `fromList` as well as `fromListN`. I can probably give it a shot later today or tomorrow.

**Comment by skeuchel** [comment]
@treeowl I'm already preparing a PR for this

**Comment by cartazio** [comment]
Ok.  True!

One thing we could do is add the from/to list instances, and then have the
associated read show code just use the list a instances underneath. Which
would mean we drop the fromlist rendering.  And thus reduce the complexity
burden.

I kinda regard read and show as debugging tools that should interact well
with source code inclusion rather than as a stable serialization tool.
Though I do agree it should roundtrip safely. (Though actual use of read .
show is a dangerously bad idea in general. )

**Comment by cartazio** [comment]
I’d ask we switch to having an IsList instance and then use the list based
read and show rep. I’d rather have our stuff just be whatever base does for
lists. I’m open to the other approaches. But keeping things simple seems
ideal. And including fromList in the parser seems to be asking for pain ..

**Comment by andrewthad** [comment]
I’m also in favor of using the OverloadedLists syntax for these. It makes them super easy to write, and as the user it’s more pleasant since the show instance has less noise. But if we’re doing this, we should change them all to be like this.

**Comment by treeowl** [comment]
Sorry, @skeuchel, I put my PR together before I saw your message saying you were doing so. Could you take a look at mine and see if you have any gripes?

**Comment by skeuchel** [comment]
@treeowl no worries ;) I'll comment on the PR.
