### ISSUE TITLE
Missing `copyPtrToMutableByteArray` in `Data.Primitive.Ptr`

### ISSUE THREAD

**Issue by ekmett** [haskell/primitive#253]
We can `copyPtrToMutablePrimArray` but not `copyPtrToMutableByteArray`. This causes users to jump through a bunch of silly hoops packing and unpacking things into different types.

**Comment by cartazio** [comment]
@Avi-D-coder as penance maybe this and 1-2 other patches? :)

**Comment by Avi-D-coder** [comment]
I'll take a look :)

**Comment by cartazio** [comment]
looking into this, its a tad more nuanced than i thought! 
@ekmett 
for `copyPtrToMutableByteArray`
what type signature are you expecting?
i'm fuzzily thinking 
```
forall m a. (PrimMonad m)
  => MutableByteArray (PrimState m) -- ^ destination array
  -> Int -- ^ destination offset
  -> Ptr a -- ^ source pointer
  -> Int -- ^ number bytes to read off the pointer 
  -> Int -- ^ number of times to copy that range into target
  -> m ()
```
so its basically a memset?

**Comment by cartazio** [comment]
cc @chessai @andrewthad  for thoughts

**Comment by chessai** [comment]
@cartazio i think it's just https://hackage.haskell.org/package/primitive-0.6.4.0/docs/Data-Primitive-Addr.html#v:copyAddrToByteArray

**Comment by cartazio** [comment]
oh, cool, yeah thats easy :)

**Comment by cartazio** [comment]
Is there anything else missing from the Ptr module atm?

**Comment by andrewthad** [comment]
This was resolved in https://github.com/haskell/primitive/pull/276. Note however that the implementation differs slightly from @chessai's suggestion. The element type in the pointer is respected by the copy, so there is a `Prim` constraint on `a`. To have the offset and length treated as bytes instead of elements of type `a`, call `castPtr @Foo @Word8 ptr` first.
