### ISSUE TITLE
sizeofSmallMutableArray

### ISSUE THREAD

**Issue by treeowl** [haskell/primitive#373]
Should we deprecate it now that `SmallArray`s can shrink in place? I'm not sure. It's a bit bogus, but it still works for code that doesn't use shrinking at all.

**Comment by treeowl** [comment]
In https://github.com/haskell/primitive/pull/372#issuecomment-1461015632, I wrote

> The situation is slightly more complicated than that, I think. Originally, there was no primop for shrinking in place; "resizing" always meant copying. So a pure function for the size was totally fine. Now that there is a shrinking primop, we need to have an IO action to be sure to get the most recent size, rather than one that might be CSEed from earlier. However, it's arguably okay to use it in a program that doesn't use shrinking. Most programs, indeed, don't use shrinking.

That said, deprecation might well be a good idea. The pure/unsafe function definitely smells like a foot-gun.

**Comment by lehins** [comment]
Same question should also apply to [`sizeofMutableByteArray`](https://hackage.haskell.org/package/primitive-0.8.0.0/docs/Data-Primitive-ByteArray.html#v:sizeofMutableByteArray)

I'd suggest deprecating them in favor monadic counterparts, because whenever one is dealing with a mutable array they are already in a some PrimMonad, so this is not much of an inconvenience, but definite improvement with respect to safety.

**Comment by chessai** [comment]
I'm in favour of deprecating both.

**Comment by konsumlamm** [comment]
This has been addressed in #387.
