### ISSUE TITLE
MutVar built on bytearray

### ISSUE THREAD

**Issue by andrewthad** [haskell/primitive#38]
This is sort of a "is this even possible?" question. The `primitive` library offers `Array` and `ByteArray`, the latter of which gives us a way to work on unboxed arrays of primitive types. Interestingly, there is no `BtyeMutVar` that acts as an unboxed `MutVar`. Is such a type possible?

**Comment by dolio** [comment]
Certainly it's possible, using an array of length 1 (which may be more than 1 byte). I seem to recall from discussion with @ekmett that there is something sub-optimal about something in this space, but I don't think the unboxed version was the 'bad' case (rather, the unlifted-but-still-a-pointer was sub-optimal as an array rather than a genuine mutvar).

**Comment by ekmett** [comment]
Reference implementation (no pun intended): https://github.com/ekmett/transients/blob/master/src/Data/Transient/Primitive/PrimRef.hs

**Comment by ekmett** [comment]
I started playing around with a different encoding that was quite a bit crazier, building a thing that can live on the heap, with a custom c-- entry point that let you modify the contents, set up so that it looks like an data constructor otherwise. So the heap representation is just a couple of words, one indicating it is an IntRef, and the next the actual number. Then with some finagling you might be able to treat this as something that lives in kind * which looks like a data constructor, providing access to its one field through a combinator that enters it to resolve it to a constructor and then can match on the field, and which scribbles the modifications in place. By doing it this way it could "freeze" in situ to an actual Int or Double constructor as it'd have the same representation, as it being 'mutable' doesn't affect the behavior. This would require a bit more interesting class than Storable or whatever I used though.

**Comment by andrewthad** [comment]
I’m going to close this.  The answer was yes, it is possible. However, you still end up with an indirection to a machine word,  which is pretty disappointing.  There is a GHC proposal  for mutable data constructor fields  that offers a more performant solution  to the same types of problems that one would solve with what I proposed here. Hopefully, in time,  it may be approved and implemented.

**Comment by ekmett** [comment]
Note: Building a 1-entry `ByteArray` is still better than building an `IORef` or `STRef` that holds, say, a haskell `Int` by one indirection.
