### ISSUE TITLE
Sever PrimBase and PrimState from PrimMonad

### ISSUE THREAD

**Issue by treeowl** [haskell/primitive#43]
If `PrimMonad` were removed as a superclass of `PrimBase`, and `PrimState` made an independent type family, then we could have

```haskell
type instance PrimState STM = RealWorld

instance PrimBase STM where
  internal (STM f) = f
```

We can't go the other way around because `STM` is not a legitimate instance of `PrimMonad` (we'd effectively have `primitive f = unsafeIOToSTM (IO f)`, which is no good).

**Comment by treeowl** [comment]
As a tiny extra bonus, we would also get

```haskell
type instance PrimState (Tagged s) = s
instance PrimBase (Tagged s) where
  internal (Tagged a) = \ s -> (# s, a #)

type instance PrimState (IdentityT f) = PrimState f
instance PrimBase f => PrimBase (IdentityT f) where
  internal (IdentityT x) = internal x
```

There may or may not be non-trivial cases other than STM; I'm not sure.

**Comment by treeowl** [comment]
Actually, it would also make good sense to add a superclass to `PrimMonad` and `PrimBase` equivalent to [MonadRef](https://hackage.haskell.org/package/ref-tf-0.4.0.1/docs/Control-Monad-Ref.html). The `MutVar` operations would get `PrimRef` (or whatever you want to call it) constraints instead of `PrimMonad` ones. I guess we could associate `PrimState` with `PrimRef`, but leaving it as a free type family seems less likely to lead to future trouble.

**Comment by cartazio** [comment]
What would these changes allow?

Io and stm codes can not be safely nested.  As nested stm codes will abort
and Io actions pretending to be stm will not have well with respect to
transactionality


There are three publicly safe ish prim base siblings, ST, IO, and the STE
monad in my monad-ste package. Even those have some subtle side conditions.

It is entirely unclear to me how those type classe changes would benefit
any current users of primitive. What would this let me say that I would be
excited about?

With the current class structure, I can use primBase to write code that
uses any monad prim enabled machinery and guarantee that I can safely
(modulo certain details about state tokens and exception handling)  mix and
match and interleave code in the constituent representations and have clear
semantics about what any exception free execution would have.

Could you help me understand what power this would enable? I'm having a
hard time grasping at it. Also there's a lot of efforts at monadRef
abstractions. And the problem is they all... Aren't uniform semantics

**Comment by treeowl** [comment]
I'm sorry; my `STM` instance was off; it should have used

```haskell
internal m | IO f <- atomically m = f
```

I have thoughts about the rest, but I have to drive home now; I'll add another comment later.

`PrimMonad` is essentially a generalization of `MonadIO`. It expresses

**Comment by dolio** [comment]
Having `STM` be involved just seems like a negative to me. It just makes various functions in primitive have the semantics of `atomically` (possibly with lifting afterward) with much less clear names, which sounds bad, not good.

All the ref stuff also can't apply to `STM`, because I'm pretty sure it's incorrect to make use of non-transactional (concurrent) stuff inside a transaction (and `TVars` are completely separate from `MutVars`). So I'm not seeing the motivation for splitting that out, either.

**Comment by treeowl** [comment]
Argh. I didn't realize that `TVar` uses a totally different primitive type. That's annoying, and supporting it would change the structure of a lot of other things.

**Comment by infinity0** [comment]
Yes I am a bit late to the party but I just discovered this myself, so commenting a follow-up:

@treeowl I am not sure why you say they use a different primitive type, they seem to [use the same type to me](https://hackage.haskell.org/package/base-4.12.0.0/docs/src/GHC.Conc.Sync.html#STM) - i.e. `(State# s -> (#State# s, a#))` precisely what `primitive` is based on. However as discussed above, if you try this in practise you get segfaults etc:

```haskell
{-# LANGUAGE BangPatterns  #-}
{-# LANGUAGE MagicHash     #-}
{-# LANGUAGE UnboxedTuples #-}

import Control.Monad.Primitive
import GHC.Conc
import GHC.Exts

main :: IO ()
main = do
  var <- atomically $ newTVar (1 :: Integer)
  let !(TVar var#) = var
  let st = readTVar# var#
  primitive st -- segfaults, we are running STM operations directly in IO
  pure ()
```

The primitive type contains calls to [haskell primops](https://gitlab.haskell.org/ghc/ghc/blob/master/compiler/prelude/primops.txt.pp) that cannot be mixed together, yet these restrictions are not expressed in the type system unfortunately. Perhaps in theory `primitives` could come up with such a system, but ideally it would be done in the base libraries themselves.
