### ISSUE TITLE
Is alignment# used for anything

### ISSUE THREAD

**Issue by andrewthad** [haskell/primitive#50]
I can see the implementations of `alignment#` and `alignment`, but I cannot find anywhere in `primitive` or in `vector` that either of these are used. The reason I am asking this is that I have a `Word48` type that I am trying to write a `Primitive` instance for, and I could just set `alignment#` to either 6 or 8, but it doesn't seem like it really matters.

**Comment by cartazio** [comment]
Benchmark :)
There's probably a time space tradeoff :)

**Comment by dolio** [comment]
It'd be used in conjunction with creating `Ptr` or `Addr` values. primitive doesn't provide that now, but perhaps it could. Even if not, people who create `Ptr` based things would want it. I don't think GHC's garbage collected byte arrays have any guaranteed alignment, otherwise vector should probably be using it when creating arrays like the ones in `Data.Vector.Primitive.Mutable`. That's why you don't see it anywhere.

**Comment by cartazio** [comment]
We should look into adding support to ghc for higher alignment relocatable
byte arrays. Would be super handy :)

**Comment by cartazio** [comment]
Pinned byte arrays can be aligned. Non pinned ones can't

**Comment by andrewthad** [comment]
I'm going to close the because I believe the original question has been answered. Currently, `alignment#` is unused. It's conceivably useful for allocating memory for `Ptr`/`Addr`. If we want to have copies of `alloca` and `malloc` from `Foreign.Marshal.Alloc` that require a `Prim` constraint instead of a `Storable` constraint, that would put it to good use (and they would be easy to implement). However, I don't need these, and it's a subject for a different issue, if anyone feels the need to open it.
