### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by kolmodin** [haskell/primitive#52]
I'd be great if there was a version of `primitive` released on Hackage that supported the upcoming GHC 8.2.1. Testing GHC 8.2.1 today is harder than it has to be, since trying to install packages fails on `primitive`.

**Comment by RyanGlScott** [comment]
Note that installing `primitive` works fine with GHC 8.2 if you just use `cabal install --allow-newer`. The only thing that we'd need to change are the upper version bounds on `base` (fixed in `primitive` HEAD in 519ca136e36caa141ac9d70e56749b0312a2991e), so we could even get away with just changing the metadata on Hackage.

**Comment by kolmodin** [comment]
``--allow-newer`` was a great trick, it allowed me to proceed.
Yes, I saw 519ca13 so I thought it'd be easy enough to release a new version.

**Comment by cartazio** [comment]
@dolio @hvr should we just do trustee style version bound tweak?

**Comment by dolio** [comment]
Bumped the base dependency on hackage.
